### ISSUE TITLE
执行nowa server提示Cannot find module 'watchpack'

### ISSUE THREAD

**Issue by zjzno1** [saltjs/salt-ui#24]
在sudo npm install watchpack --save 后执行 nowa server 还报这个错。。求解决方案。。。

module.js:442
    throw err;
    ^
Error: Cannot find module 'watchpack'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/zjz/.nowa/install/webpack/1.13.3/webpack/lib/node/NodeWatchFileSystem.js:5:17)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

**Comment by zjzno1** [comment]
是mac系统，有遇到同样问题的同学吗？

**Comment by gbk** [comment]
https://github.com/nowa-webpack/nowa/issues/17
试试看卸载重装能否解决？npminstall 不太稳定

**Comment by gbk** [comment]
@zjzno1 

sudo npm uninstall nowa -g
sudo npm cache clean
sudo rm -rf ~/.nowa ~/.npminstall_tarball
sudo npm i nowa -g --registry=https://registry.npm.taobao.org
sudo chmod 777 \`npm root -g\`
nowa install --registry=https://registry.npm.taobao.org

**Comment by zjzno1** [comment]
@gbk 我把nowa卸载掉清缓存重新装了可以了，谢谢啦。
