### ISSUE TITLE
demo中,avatar例子定义全局变量报错

### ISSUE THREAD

**Issue by canca** [saltjs/salt-ui#3]
demo中,avatar例子定义全局变量报错
`global.colors = ['green', 'grey', 'orange', 'blue', 'red'];`

报以下错误：
`请在钉钉App打开此页面
Uncaught TypeError: Cannot set property 'colors' of undefined
[React Transform HMR] There was an error updating D:/nodejs/demo/src/pages/demo/PageDemo.js:
TypeError: Cannot set property 'colors' of undefined
    at Object.<anonymous> (http://10.10.10.119:3000/0.e2a6989ce238fab4e719.hot-update.js:77:16)
    at Object.176 (http://10.10.10.119:3000/0.e2a6989ce238fab4e719.hot-update.js:110:31)
    at __webpack_require__ (http://10.10.10.119:3000/app.js:556:30)
    at Object.hotApply [as apply] (http://10.10.10.119:3000/app.js:511:14)
    at cb (http://10.10.10.119:3000/app.js:1789:37)
    at hotUpdateDownloaded (http://10.10.10.119:3000/app.js:312:13)
    at hotAddUpdateChunk (http://10.10.10.119:3000/app.js:284:13)
    at webpackHotUpdateCallback (http://10.10.10.119:3000/app.js:5:12)
    at http://10.10.10.119:3000/0.e2a6989ce238fab4e719.hot-update.js:1:1
`

**Comment by alex-mm** [comment]
哪里的 demo ？

**Comment by canca** [comment]
这个解决了，重装一下就OK了。

**Comment by 2999** [comment]
从提问题到现在，有多次迭代发布，不知是否已修复你的问题。@canca ，如有问题，再提issue。
